<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-A24CO29" failures="1" tests="2" name="Submitordertest" time="75.723" errors="0" timestamp="2024-03-10T19:09:40 IST">
  <testcase classname="Framework_test.Automation_framework.E2Etest" name="submitorder" time="26.529">
    <skipped/>
  </testcase> <!-- submitorder -->
  <testcase classname="Framework_test.Automation_framework.E2Etest" name="submitorder" time="35.736">
    <failure type="java.lang.AssertionError" message="expected [THANKYOU FOR THE ORDERs.] but found [THANKYOU FOR THE ORDER.]">
      <![CDATA[java.lang.AssertionError: expected [THANKYOU FOR THE ORDERs.] but found [THANKYOU FOR THE ORDER.]
at Framework_test.Automation_framework.E2Etest.submitorder(E2Etest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- submitorder -->
</testsuite> <!-- Submitordertest -->
